//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Final_project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audiance {
            get {
                object obj = ResourceManager.GetObject("audiance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audiance_used {
            get {
                object obj = ResourceManager.GetObject("audiance_used", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call {
            get {
                object obj = ResourceManager.GetObject("call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call_used {
            get {
                object obj = ResourceManager.GetObject("call_used", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Р§С‚Рѕ СЂР°СЃС‚С‘С‚ РІ РѕРіРѕСЂРѕРґРµ?
        ///1.Р›СѓРє
        ///2.РџРёСЃС‚РѕР»РµС‚
        ///3.РџСѓР»РµРјС‘С‚
        ///4.Р Р°РєРµС‚Р° РЎРЎ-20
        ///  1
        ///
        ///2. РљР°Рє РЅР°Р·С‹РІР°СЋС‚ РјРёРєСЂРѕР°РІС‚РѕР±СѓСЃС‹, СЃРѕРІРµСЂС€Р°СЋС‰РёРµ РїРѕРµР·РґРєРё РїРѕ РѕРїСЂРµРґРµР»С‘РЅРЅС‹Рј РјР°СЂС€СЂСѓС‚Р°Рј?
        ///1.Р РµР№СЃРѕРІРєР°
        ///2.РџСѓС‚С‘РІРєР°
        ///3.РљСѓСЂСЃРѕРІРєР°
        ///4.РњР°СЂС€СЂСѓС‚РєР°
        /// 4
        ///
        ///3. Рћ С‡С‘Рј РїРёСЃР°Р» Р“СЂРёР±РѕРµРґРѕРІ, РѕС‚РјРµС‡Р°СЏ, С‡С‚Рѕ РѕРЅ В«РЅР°Рј СЃР»Р°РґРѕРє Рё РїСЂРёСЏС‚РµРЅВ» ?
        ///1.Р”С‹Рј РћС‚РµС‡РµСЃС‚РІР°
        ///2.Р”СѓС… РєСѓР [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset_for_game {
            get {
                return ResourceManager.GetString("dataset_for_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fifty {
            get {
                object obj = ResourceManager.GetObject("fifty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fifty_used {
            get {
                object obj = ResourceManager.GetObject("fifty_used", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра Кто хочет стать миллионером? - это конкурс викторина, 
        ///в котором участники должны правильно ответить на ряд вопросов 
        ///с несколькими вариантами ответов, чтобы перейти на следующий уровень. 
        ///Всего 20 вопросов, каждый вопрос стоит определенной суммы денег, 
        ///участники не имеют никаких временных ограничений для предоставления ответа. 
        ///Участники также получают три вида подсказок, чтобы помочь себе, если они застряли на конкретном вопросе.
        ///
        ///Участникам разрешается применить три подсказки, которые они мо [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap win {
            get {
                object obj = ResourceManager.GetObject("win", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
